name: Run Test Collection

on:
  workflow_dispatch:

jobs:
  call-pm-passing-data:
    uses: .LuisTejedaS/pm-gh/.github/workflows/run-postman-collection.yml
    with:
      collection_name: "postman/testCollection.json"
      environment_name: "postman/tetEnvironment.json"
    secrets:
      API_KEY: ${{ secrets.API_KEY }}